### ISSUE TITLE
"Press any key to continue setup..." expects enter key to be pressed

### ISSUE THREAD

**Issue by wojtekn** [mage2click/docker-magento-mutagen#78]
"Press any key to continue setup..." prompt is displayed and it doesn't allow to proceed unless Enter key is pressed.

It looks that simplest fix would be about changing "any key" to "enter", but it's also possible to adjust `read` call to accept any key.

**Comment by shkoliar** [comment]
Thanks, @wojtekn! Good catch

**Comment by shkoliar** [comment]
Added PR #79 with the fix, will be merged once @u-maxx adds his review on it

**Comment by u-maxx** [comment]
Thank you @wojtekn !
