### ISSUE TITLE
Add support for libsodium for PHP 7.2

### ISSUE THREAD

**Issue by atishgoswami** [mage2click/docker-magento-mutagen#86]
Magento 2.3.2 requires libsodium to install properly.

https://github.com/magento/magento2/issues/23405

Need to have libsodium pre install in the PHP containers

**Comment by atishgoswami** [comment]
Seems like the sodium extension is already installed but outdated, Magento expects the sodium library version >= 1.0.13.

Used this link below to update the sodium library version
http://blog.grafzahl.io/magento-warning-after-updating-to-2-3-2/

**Comment by shkoliar** [comment]
Hello, @atishgoswami!

Thank you for your interest to our project!

We've added libsodium to 7.1 and 7.2 PHP versions, check this PR https://github.com/mage2click/magento-php-versions/pull/9
