### ISSUE TITLE
Formulae found in multiple taps

### ISSUE THREAD

**Issue by itsazzad** [mage2click/docker-magento-mutagen#94]
```
Error: Formulae found in multiple taps: 
       * havoc-io/mutagen/mutagen
       * mutagen-io/mutagen/mutagen

Please use the fully-qualified name (e.g. havoc-io/mutagen/mutagen) to refer to the formula.
```

**Comment by itsazzad** [comment]
https://github.com/mutagen-io/mutagen/issues/122#issuecomment-516547003

**Comment by Lanot** [comment]
These few commands worked for me (MacOS):
brew untap havoc-io/mutagen && brew untap mutagen-io/mutagen
brew install mutagen-io/mutagen/mutagen

**Comment by VivekShingala** [comment]
Thanks @Lanot 

It worked for me.
